apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/: "true"
  name: cmo.monitoring.openshift.io
spec:
  group: monitoring.openshift.io
  names:
    kind: ClusterMonitoringOperatorList
    listKind: ClusterMonitoringOperatorListList
    plural: cmo
    singular: clustermonitoringoperatorlist
  scope: Cluster
  versions:
  - name: v1
    served: true
    storage: true
